import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import type { Metadata } from 'next'
import { roboto, rowdies } from './fonts'
import './globals.css'

export const metadata: Metadata = {
    title: 'Reliable Painters',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={`${roboto.variable} ${rowdies.variable} scroll-smooth`}>
            <body>
                <AppRouterCacheProvider>
                    {children}
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
